baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "leanovate-presentation"
pygmentsstyle = "colorful"

[taxonomies]
  presentation = "presentations"
